using DataFrames
using Dates
using RCall

"""
    generate_front_matter(vars::Dict{String,String})

Generates YAML front matter based on given `vars`.
"""
function generate_front_matter(vars::Dict{String,String})::String
    if !("date" in keys(vars))
        vars["date"] = string(Dates.today())
    end

    as_line(key::String) = "$(key): $(vars[key])"
    lines = join(map(as_line, collect(keys(vars))), '\n')
    """
    ---
    $lines
    ---

    [//]: # (GENERATED FILE. DO NOT MODIFY.)

    """
end
export generate_front_matter

"""
    df2md(df::DataFrame)

Convert DataFrame to String.
"""
function df2md(df::DataFrame; show_header=true)::String
  row2str(row::DataFrameRow) = join(values(row), " | ")

  if show_header 
    header = join(names(df), " | ")
  else
    header = join(repeat([' '], ncol(df)), " | ")
  end
  subheader = join(repeat(["---"], ncol(df)), " | ")
  body = join(map(i -> row2str(df[i, :]), 1:nrow(df)), '\n')
  
  return """
  $header
  $subheader
  $body
  """
end
export df2md

"""
    rplot

Transform R plot `plot` object to string.
The plot will be stored at `path_prefix / filename`.
The string will point to an image generated by the R plot, located at `uri_prefix / filename`.

To avoid constantly passing `path_prefix` and `url_prefix`, consider using partial function application.
"""
function rplot(plot, filename, path_prefix, uri_prefix)::String
    im_path = joinpath(path_prefix, filename)
    R"ggsave(file=$im_path, plot=$plot)"
    uri_path = joinpath(uri_prefix, filename)
    return uri_path
end
export rplot

"""
    @asmd ex

Returns an expresssion *as Markdown* (asmd).
Similar to default behaviour of R Markdown codeblocks.
"""
macro asmd(ex::Expr)
    return """
        ```
        $(ex)
        ```
        $(eval(ex))
        """
end
export @asmd
