# This workflow is based on https://github.com/andyferris/Dictionaries.jl.
name: Test
on:
  push:
    branches:
      - master
    tags: '*'
  pull_request:
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    continue-on-error: ${{ matrix.version == 'nightly' }}
    strategy:
      matrix:
        version:
          - '1.4'
        os:
          - ubuntu-latest
        arch:
          - x64
    steps:
      - uses: actions/checkout@v1
      - uses: r-lib/actions/setup-r@v1
      - run: echo "::set-env name=LD_LIBRARY_PATH::$(R RHOME)/lib"
      - run: apt-get install -y r-recommended
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-runtest@latest
